# Generated by Django 5.2.3 on 2025-06-16 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Periodicity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(verbose_name="Значение периодичности"),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("minutes", "Минуты"),
                            ("hours", "Часы"),
                            ("days", "Дни"),
                            ("weeks", "Недели"),
                        ],
                        max_length=10,
                        verbose_name="Единица измерения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Периодичность",
                "verbose_name_plural": "Периодичности",
            },
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="habits.periodicity",
                verbose_name="Периодичность выполнения",
            ),
        ),
    ]
