# Generated by Django 5.2.3 on 2025-06-18 16:17

from django.db import migrations


def set_default_periodicity(apps, schema_editor):
    Periodicity = apps.get_model("habits", "Periodicity")
    Habit = apps.get_model("habits", "Habit")

    daily, created = Periodicity.objects.get_or_create(
        value=1, unit="days", defaults={"value": 1, "unit": "days"}
    )

    Habit.objects.filter(periodicity__isnull=True).update(periodicity=daily)


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_periodicity"),
    ]

    operations = [
        migrations.RunPython(set_default_periodicity),
    ]
