# Generated by Django 5.2.3 on 2025-06-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_auto_20250618_1917"),
    ]

    operations = [
        migrations.AlterField(
            model_name="periodicity",
            name="unit",
            field=models.CharField(
                choices=[
                    ("minutes", "минута/минуты/минут"),
                    ("hours", "час/часа/часов"),
                    ("days", "день/дня/дней"),
                    ("week", "неделя/недели/недель"),
                ],
                max_length=10,
                verbose_name="Единица измерения",
            ),
        ),
    ]
