# Generated by Django 5.2.3 on 2025-06-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_alter_periodicity_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time_to_complete",
            field=models.PositiveIntegerField(
                verbose_name="Время на выполнение (в секундах)"
            ),
        ),
    ]
