# Generated by Django 5.2.3 on 2025-06-20 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0006_alter_habit_time_to_complete"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={
                "ordering": ["id"],
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
